import unittest
from nextactions.card import Card


class TestCard(unittest.TestCase):

    def testIsAutoGenerated(self):
        json = {
            'id': "1",
            'name': "Card",
            'idBoard': "2",
            'desc': "Thing",
            'url': "fake"
        }
        card1 = Card(json)
        card2 = Card(json)
        card2.description = card2.description + " " + Card.AUTO_GENERATED_TEXT
        self.assertFalse(card1.isAutoGenerated())
        self.assertTrue(card2.isAutoGenerated())
