class Card:

    AUTO_GENERATED_TEXT = 'Auto-created by TrelloNextActions'

    def __init__(self, json):
        self.id = json['id']
        self.name = json['name']
        self.board_id = json['idBoard']
        self.description = json['desc']
        self.url = json['url']

    def isAutoGenerated(self):
        return Card.AUTO_GENERATED_TEXT in self.description
