from urllib.parse import urlparse


class Card:

    AUTO_GENERATED_TEXT = 'Auto-created by TrelloNextActions'

    def __init__(self, trello, json):
        self._trello = trello
        self.id = json['id']
        self.name = json['name']
        self.board_id = json['idBoard']
        self.description = json['desc']
        self.url = json['url']

    def isAutoGenerated(self):
        return Card.AUTO_GENERATED_TEXT in self.description

    def getProjectBoard(self):
        board_id = self._getProjectBoardId()
        return self._trello.getBoardById(board_id)

    def _getProjectBoardId(self):
        url_components = urlparse(self.description)
        path_segments = url_components.path.split('/')
        if (len(path_segments) >= 3):
            return path_segments[2]
        else:
            raise ValueError("Description could not be parsed as project URL")
