class SyncTool:

    def __init__(self, config, trello):
        self._config = config
        self._trello = trello

    def getNextActionCards(self):
        board = self._trello.getBoardById(self._config.get('gtd_board_id'))
        list_ = board.getListByName('Next Actions')
        return [c for c in list_.getCards() if c.isAutoGenerated()]

    def reset(self):
        for c in self.getNextActionCards():
            self._trello.archiveCard(c.id)
